// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NoriClient is the client API for Nori service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoriClient interface {
	//plugin
	PluginEnable(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginDisable(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginGet(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginInstall(ctx context.Context, in *PluginInstallRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginInterface(ctx context.Context, in *PluginInterfaceRequest, opts ...grpc.CallOption) (*PluginListReply, error)
	PluginList(ctx context.Context, in *PluginListRequest, opts ...grpc.CallOption) (*PluginListReply, error)
	PluginMeta(ctx context.Context, in *PluginMetaRequest, opts ...grpc.CallOption) (*PluginMetaReply, error)
	PluginPull(ctx context.Context, in *PluginPullRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginRemove(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginStart(ctx context.Context, in *PluginStartRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginStop(ctx context.Context, in *PluginStopRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginUninstall(ctx context.Context, in *PluginUninstallRequest, opts ...grpc.CallOption) (*Reply, error)
	PluginUpload(ctx context.Context, opts ...grpc.CallOption) (Nori_PluginUploadClient, error)
	//config
	ConfigGet(ctx context.Context, in *ConfigGetRequest, opts ...grpc.CallOption) (*ConfigGetReply, error)
	ConfigSet(ctx context.Context, in *ConfigSetRequest, opts ...grpc.CallOption) (*ConfigSetReply, error)
	ConfigUpload(ctx context.Context, in *ConfigUploadRequest, opts ...grpc.CallOption) (*ConfigUploadReply, error)
}

type noriClient struct {
	cc grpc.ClientConnInterface
}

func NewNoriClient(cc grpc.ClientConnInterface) NoriClient {
	return &noriClient{cc}
}

func (c *noriClient) PluginEnable(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginEnable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginDisable(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginDisable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginGet(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginInstall(ctx context.Context, in *PluginInstallRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginInstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginInterface(ctx context.Context, in *PluginInterfaceRequest, opts ...grpc.CallOption) (*PluginListReply, error) {
	out := new(PluginListReply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginList(ctx context.Context, in *PluginListRequest, opts ...grpc.CallOption) (*PluginListReply, error) {
	out := new(PluginListReply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginMeta(ctx context.Context, in *PluginMetaRequest, opts ...grpc.CallOption) (*PluginMetaReply, error) {
	out := new(PluginMetaReply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginPull(ctx context.Context, in *PluginPullRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginPull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginRemove(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginStart(ctx context.Context, in *PluginStartRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginStop(ctx context.Context, in *PluginStopRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginUninstall(ctx context.Context, in *PluginUninstallRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/proto.Nori/PluginUninstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) PluginUpload(ctx context.Context, opts ...grpc.CallOption) (Nori_PluginUploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Nori_ServiceDesc.Streams[0], "/proto.Nori/PluginUpload", opts...)
	if err != nil {
		return nil, err
	}
	x := &noriPluginUploadClient{stream}
	return x, nil
}

type Nori_PluginUploadClient interface {
	Send(*PluginUploadChunk) error
	CloseAndRecv() (*Reply, error)
	grpc.ClientStream
}

type noriPluginUploadClient struct {
	grpc.ClientStream
}

func (x *noriPluginUploadClient) Send(m *PluginUploadChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *noriPluginUploadClient) CloseAndRecv() (*Reply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *noriClient) ConfigGet(ctx context.Context, in *ConfigGetRequest, opts ...grpc.CallOption) (*ConfigGetReply, error) {
	out := new(ConfigGetReply)
	err := c.cc.Invoke(ctx, "/proto.Nori/ConfigGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) ConfigSet(ctx context.Context, in *ConfigSetRequest, opts ...grpc.CallOption) (*ConfigSetReply, error) {
	out := new(ConfigSetReply)
	err := c.cc.Invoke(ctx, "/proto.Nori/ConfigSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noriClient) ConfigUpload(ctx context.Context, in *ConfigUploadRequest, opts ...grpc.CallOption) (*ConfigUploadReply, error) {
	out := new(ConfigUploadReply)
	err := c.cc.Invoke(ctx, "/proto.Nori/ConfigUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoriServer is the server API for Nori service.
// All implementations must embed UnimplementedNoriServer
// for forward compatibility
type NoriServer interface {
	//plugin
	PluginEnable(context.Context, *PluginRequest) (*Reply, error)
	PluginDisable(context.Context, *PluginRequest) (*Reply, error)
	PluginGet(context.Context, *PluginRequest) (*Reply, error)
	PluginInstall(context.Context, *PluginInstallRequest) (*Reply, error)
	PluginInterface(context.Context, *PluginInterfaceRequest) (*PluginListReply, error)
	PluginList(context.Context, *PluginListRequest) (*PluginListReply, error)
	PluginMeta(context.Context, *PluginMetaRequest) (*PluginMetaReply, error)
	PluginPull(context.Context, *PluginPullRequest) (*Reply, error)
	PluginRemove(context.Context, *PluginRequest) (*Reply, error)
	PluginStart(context.Context, *PluginStartRequest) (*Reply, error)
	PluginStop(context.Context, *PluginStopRequest) (*Reply, error)
	PluginUninstall(context.Context, *PluginUninstallRequest) (*Reply, error)
	PluginUpload(Nori_PluginUploadServer) error
	//config
	ConfigGet(context.Context, *ConfigGetRequest) (*ConfigGetReply, error)
	ConfigSet(context.Context, *ConfigSetRequest) (*ConfigSetReply, error)
	ConfigUpload(context.Context, *ConfigUploadRequest) (*ConfigUploadReply, error)
	mustEmbedUnimplementedNoriServer()
}

// UnimplementedNoriServer must be embedded to have forward compatible implementations.
type UnimplementedNoriServer struct {
}

func (UnimplementedNoriServer) PluginEnable(context.Context, *PluginRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginEnable not implemented")
}
func (UnimplementedNoriServer) PluginDisable(context.Context, *PluginRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginDisable not implemented")
}
func (UnimplementedNoriServer) PluginGet(context.Context, *PluginRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginGet not implemented")
}
func (UnimplementedNoriServer) PluginInstall(context.Context, *PluginInstallRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginInstall not implemented")
}
func (UnimplementedNoriServer) PluginInterface(context.Context, *PluginInterfaceRequest) (*PluginListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginInterface not implemented")
}
func (UnimplementedNoriServer) PluginList(context.Context, *PluginListRequest) (*PluginListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginList not implemented")
}
func (UnimplementedNoriServer) PluginMeta(context.Context, *PluginMetaRequest) (*PluginMetaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginMeta not implemented")
}
func (UnimplementedNoriServer) PluginPull(context.Context, *PluginPullRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginPull not implemented")
}
func (UnimplementedNoriServer) PluginRemove(context.Context, *PluginRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginRemove not implemented")
}
func (UnimplementedNoriServer) PluginStart(context.Context, *PluginStartRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginStart not implemented")
}
func (UnimplementedNoriServer) PluginStop(context.Context, *PluginStopRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginStop not implemented")
}
func (UnimplementedNoriServer) PluginUninstall(context.Context, *PluginUninstallRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginUninstall not implemented")
}
func (UnimplementedNoriServer) PluginUpload(Nori_PluginUploadServer) error {
	return status.Errorf(codes.Unimplemented, "method PluginUpload not implemented")
}
func (UnimplementedNoriServer) ConfigGet(context.Context, *ConfigGetRequest) (*ConfigGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigGet not implemented")
}
func (UnimplementedNoriServer) ConfigSet(context.Context, *ConfigSetRequest) (*ConfigSetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigSet not implemented")
}
func (UnimplementedNoriServer) ConfigUpload(context.Context, *ConfigUploadRequest) (*ConfigUploadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigUpload not implemented")
}
func (UnimplementedNoriServer) mustEmbedUnimplementedNoriServer() {}

// UnsafeNoriServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoriServer will
// result in compilation errors.
type UnsafeNoriServer interface {
	mustEmbedUnimplementedNoriServer()
}

func RegisterNoriServer(s grpc.ServiceRegistrar, srv NoriServer) {
	s.RegisterService(&Nori_ServiceDesc, srv)
}

func _Nori_PluginEnable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginEnable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginEnable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginEnable(ctx, req.(*PluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginDisable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginDisable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginDisable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginDisable(ctx, req.(*PluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginGet(ctx, req.(*PluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginInstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginInstall(ctx, req.(*PluginInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginInterface(ctx, req.(*PluginInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginList(ctx, req.(*PluginListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginMeta(ctx, req.(*PluginMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginPull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginPull(ctx, req.(*PluginPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginRemove(ctx, req.(*PluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginStart(ctx, req.(*PluginStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginStop(ctx, req.(*PluginStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginUninstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginUninstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).PluginUninstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/PluginUninstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).PluginUninstall(ctx, req.(*PluginUninstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_PluginUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NoriServer).PluginUpload(&noriPluginUploadServer{stream})
}

type Nori_PluginUploadServer interface {
	SendAndClose(*Reply) error
	Recv() (*PluginUploadChunk, error)
	grpc.ServerStream
}

type noriPluginUploadServer struct {
	grpc.ServerStream
}

func (x *noriPluginUploadServer) SendAndClose(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *noriPluginUploadServer) Recv() (*PluginUploadChunk, error) {
	m := new(PluginUploadChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Nori_ConfigGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).ConfigGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/ConfigGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).ConfigGet(ctx, req.(*ConfigGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_ConfigSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).ConfigSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/ConfigSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).ConfigSet(ctx, req.(*ConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nori_ConfigUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoriServer).ConfigUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nori/ConfigUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoriServer).ConfigUpload(ctx, req.(*ConfigUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nori_ServiceDesc is the grpc.ServiceDesc for Nori service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nori_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Nori",
	HandlerType: (*NoriServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PluginEnable",
			Handler:    _Nori_PluginEnable_Handler,
		},
		{
			MethodName: "PluginDisable",
			Handler:    _Nori_PluginDisable_Handler,
		},
		{
			MethodName: "PluginGet",
			Handler:    _Nori_PluginGet_Handler,
		},
		{
			MethodName: "PluginInstall",
			Handler:    _Nori_PluginInstall_Handler,
		},
		{
			MethodName: "PluginInterface",
			Handler:    _Nori_PluginInterface_Handler,
		},
		{
			MethodName: "PluginList",
			Handler:    _Nori_PluginList_Handler,
		},
		{
			MethodName: "PluginMeta",
			Handler:    _Nori_PluginMeta_Handler,
		},
		{
			MethodName: "PluginPull",
			Handler:    _Nori_PluginPull_Handler,
		},
		{
			MethodName: "PluginRemove",
			Handler:    _Nori_PluginRemove_Handler,
		},
		{
			MethodName: "PluginStart",
			Handler:    _Nori_PluginStart_Handler,
		},
		{
			MethodName: "PluginStop",
			Handler:    _Nori_PluginStop_Handler,
		},
		{
			MethodName: "PluginUninstall",
			Handler:    _Nori_PluginUninstall_Handler,
		},
		{
			MethodName: "ConfigGet",
			Handler:    _Nori_ConfigGet_Handler,
		},
		{
			MethodName: "ConfigSet",
			Handler:    _Nori_ConfigSet_Handler,
		},
		{
			MethodName: "ConfigUpload",
			Handler:    _Nori_ConfigUpload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PluginUpload",
			Handler:       _Nori_PluginUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "nori.proto",
}
