// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.6.1
// source: plugin.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// cmd: plugin get
type PluginGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *ID  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FlagVerbose bool `protobuf:"varint,2,opt,name=FlagVerbose,proto3" json:"FlagVerbose,omitempty"`
}

func (x *PluginGetRequest) Reset() {
	*x = PluginGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginGetRequest) ProtoMessage() {}

func (x *PluginGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginGetRequest.ProtoReflect.Descriptor instead.
func (*PluginGetRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginGetRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PluginGetRequest) GetFlagVerbose() bool {
	if x != nil {
		return x.FlagVerbose
	}
	return false
}

type PluginPullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ID  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FlagDeps bool `protobuf:"varint,2,opt,name=FlagDeps,proto3" json:"FlagDeps,omitempty"`
}

func (x *PluginPullRequest) Reset() {
	*x = PluginPullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginPullRequest) ProtoMessage() {}

func (x *PluginPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginPullRequest.ProtoReflect.Descriptor instead.
func (*PluginPullRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginPullRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PluginPullRequest) GetFlagDeps() bool {
	if x != nil {
		return x.FlagDeps
	}
	return false
}

// cmd: plugin install
type PluginInstallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *ID  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FlagVerbose bool `protobuf:"varint,2,opt,name=FlagVerbose,proto3" json:"FlagVerbose,omitempty"`
	FlagDeps    bool `protobuf:"varint,3,opt,name=FlagDeps,proto3" json:"FlagDeps,omitempty"`
	FlagAll     bool `protobuf:"varint,4,opt,name=FlagAll,proto3" json:"FlagAll,omitempty"`
}

func (x *PluginInstallRequest) Reset() {
	*x = PluginInstallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInstallRequest) ProtoMessage() {}

func (x *PluginInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInstallRequest.ProtoReflect.Descriptor instead.
func (*PluginInstallRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginInstallRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PluginInstallRequest) GetFlagVerbose() bool {
	if x != nil {
		return x.FlagVerbose
	}
	return false
}

func (x *PluginInstallRequest) GetFlagDeps() bool {
	if x != nil {
		return x.FlagDeps
	}
	return false
}

func (x *PluginInstallRequest) GetFlagAll() bool {
	if x != nil {
		return x.FlagAll
	}
	return false
}

type PluginInterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterfaceName string `protobuf:"bytes,1,opt,name=InterfaceName,proto3" json:"InterfaceName,omitempty"`
}

func (x *PluginInterfaceRequest) Reset() {
	*x = PluginInterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInterfaceRequest) ProtoMessage() {}

func (x *PluginInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInterfaceRequest.ProtoReflect.Descriptor instead.
func (*PluginInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginInterfaceRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

// cmd: plugin list
type PluginListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlagAll         bool `protobuf:"varint,1,opt,name=FlagAll,proto3" json:"FlagAll,omitempty"`
	FlagError       bool `protobuf:"varint,2,opt,name=FlagError,proto3" json:"FlagError,omitempty"`
	FlagInstalled   bool `protobuf:"varint,3,opt,name=FlagInstalled,proto3" json:"FlagInstalled,omitempty"`
	FlagRunning     bool `protobuf:"varint,4,opt,name=FlagRunning,proto3" json:"FlagRunning,omitempty"`
	FlagInstallable bool `protobuf:"varint,5,opt,name=FlagInstallable,proto3" json:"FlagInstallable,omitempty"`
	FlagInactive    bool `protobuf:"varint,6,opt,name=FlagInactive,proto3" json:"FlagInactive,omitempty"`
}

func (x *PluginListRequest) Reset() {
	*x = PluginListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginListRequest) ProtoMessage() {}

func (x *PluginListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginListRequest.ProtoReflect.Descriptor instead.
func (*PluginListRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginListRequest) GetFlagAll() bool {
	if x != nil {
		return x.FlagAll
	}
	return false
}

func (x *PluginListRequest) GetFlagError() bool {
	if x != nil {
		return x.FlagError
	}
	return false
}

func (x *PluginListRequest) GetFlagInstalled() bool {
	if x != nil {
		return x.FlagInstalled
	}
	return false
}

func (x *PluginListRequest) GetFlagRunning() bool {
	if x != nil {
		return x.FlagRunning
	}
	return false
}

func (x *PluginListRequest) GetFlagInstallable() bool {
	if x != nil {
		return x.FlagInstallable
	}
	return false
}

func (x *PluginListRequest) GetFlagInactive() bool {
	if x != nil {
		return x.FlagInactive
	}
	return false
}

type PluginListWithStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaID            *ID           `protobuf:"bytes,1,opt,name=metaID,proto3" json:"metaID,omitempty"`
	Author            *Author       `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	DependenciesArray *Dependencies `protobuf:"bytes,3,opt,name=DependenciesArray,proto3" json:"DependenciesArray,omitempty"`
	Description       *Description  `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Core              *Core         `protobuf:"bytes,5,opt,name=Core,proto3" json:"Core,omitempty"`
	Interface         *Interface    `protobuf:"bytes,6,opt,name=Interface,proto3" json:"Interface,omitempty"`
	License           *License      `protobuf:"bytes,7,opt,name=License,proto3" json:"License,omitempty"`
	Links             *Links        `protobuf:"bytes,8,opt,name=Links,proto3" json:"Links,omitempty"`
	Repository        *Repository   `protobuf:"bytes,9,opt,name=Repository,proto3" json:"Repository,omitempty"`
	Tags              []string      `protobuf:"bytes,10,rep,name=Tags,proto3" json:"Tags,omitempty"`
	FlagAll           bool          `protobuf:"varint,11,opt,name=FlagAll,proto3" json:"FlagAll,omitempty"`
	FlagError         bool          `protobuf:"varint,12,opt,name=FlagError,proto3" json:"FlagError,omitempty"`
	FlagInstalled     bool          `protobuf:"varint,13,opt,name=FlagInstalled,proto3" json:"FlagInstalled,omitempty"`
	FlagRunning       bool          `protobuf:"varint,14,opt,name=FlagRunning,proto3" json:"FlagRunning,omitempty"`
	FlagInstallable   bool          `protobuf:"varint,15,opt,name=FlagInstallable,proto3" json:"FlagInstallable,omitempty"`
	FlagInactive      bool          `protobuf:"varint,16,opt,name=FlagInactive,proto3" json:"FlagInactive,omitempty"`
}

func (x *PluginListWithStatus) Reset() {
	*x = PluginListWithStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginListWithStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginListWithStatus) ProtoMessage() {}

func (x *PluginListWithStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginListWithStatus.ProtoReflect.Descriptor instead.
func (*PluginListWithStatus) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PluginListWithStatus) GetMetaID() *ID {
	if x != nil {
		return x.MetaID
	}
	return nil
}

func (x *PluginListWithStatus) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *PluginListWithStatus) GetDependenciesArray() *Dependencies {
	if x != nil {
		return x.DependenciesArray
	}
	return nil
}

func (x *PluginListWithStatus) GetDescription() *Description {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *PluginListWithStatus) GetCore() *Core {
	if x != nil {
		return x.Core
	}
	return nil
}

func (x *PluginListWithStatus) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

func (x *PluginListWithStatus) GetLicense() *License {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *PluginListWithStatus) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *PluginListWithStatus) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *PluginListWithStatus) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PluginListWithStatus) GetFlagAll() bool {
	if x != nil {
		return x.FlagAll
	}
	return false
}

func (x *PluginListWithStatus) GetFlagError() bool {
	if x != nil {
		return x.FlagError
	}
	return false
}

func (x *PluginListWithStatus) GetFlagInstalled() bool {
	if x != nil {
		return x.FlagInstalled
	}
	return false
}

func (x *PluginListWithStatus) GetFlagRunning() bool {
	if x != nil {
		return x.FlagRunning
	}
	return false
}

func (x *PluginListWithStatus) GetFlagInstallable() bool {
	if x != nil {
		return x.FlagInstallable
	}
	return false
}

func (x *PluginListWithStatus) GetFlagInactive() bool {
	if x != nil {
		return x.FlagInactive
	}
	return false
}

type PluginListWithoutStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaID            *ID           `protobuf:"bytes,1,opt,name=metaID,proto3" json:"metaID,omitempty"`
	Author            *Author       `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	DependenciesArray *Dependencies `protobuf:"bytes,3,opt,name=DependenciesArray,proto3" json:"DependenciesArray,omitempty"`
	Description       *Description  `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Core              *Core         `protobuf:"bytes,5,opt,name=Core,proto3" json:"Core,omitempty"`
	Interface         *Interface    `protobuf:"bytes,6,opt,name=Interface,proto3" json:"Interface,omitempty"`
	License           *License      `protobuf:"bytes,7,opt,name=License,proto3" json:"License,omitempty"`
	Links             *Links        `protobuf:"bytes,8,opt,name=Links,proto3" json:"Links,omitempty"`
	Repository        *Repository   `protobuf:"bytes,9,opt,name=Repository,proto3" json:"Repository,omitempty"`
	Tags              []string      `protobuf:"bytes,10,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *PluginListWithoutStatus) Reset() {
	*x = PluginListWithoutStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginListWithoutStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginListWithoutStatus) ProtoMessage() {}

func (x *PluginListWithoutStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginListWithoutStatus.ProtoReflect.Descriptor instead.
func (*PluginListWithoutStatus) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *PluginListWithoutStatus) GetMetaID() *ID {
	if x != nil {
		return x.MetaID
	}
	return nil
}

func (x *PluginListWithoutStatus) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *PluginListWithoutStatus) GetDependenciesArray() *Dependencies {
	if x != nil {
		return x.DependenciesArray
	}
	return nil
}

func (x *PluginListWithoutStatus) GetDescription() *Description {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *PluginListWithoutStatus) GetCore() *Core {
	if x != nil {
		return x.Core
	}
	return nil
}

func (x *PluginListWithoutStatus) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

func (x *PluginListWithoutStatus) GetLicense() *License {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *PluginListWithoutStatus) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *PluginListWithoutStatus) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *PluginListWithoutStatus) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PluginListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        []*PluginListWithStatus `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	ErrorPlugin *ErrorReply             `protobuf:"bytes,2,opt,name=ErrorPlugin,proto3" json:"ErrorPlugin,omitempty"`
}

func (x *PluginListReply) Reset() {
	*x = PluginListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginListReply) ProtoMessage() {}

func (x *PluginListReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginListReply.ProtoReflect.Descriptor instead.
func (*PluginListReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginListReply) GetData() []*PluginListWithStatus {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PluginListReply) GetErrorPlugin() *ErrorReply {
	if x != nil {
		return x.ErrorPlugin
	}
	return nil
}

// cmd: plugin remove
type PluginRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ID `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *PluginRemoveRequest) Reset() {
	*x = PluginRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRemoveRequest) ProtoMessage() {}

func (x *PluginRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRemoveRequest.ProtoReflect.Descriptor instead.
func (*PluginRemoveRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PluginRemoveRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

type PluginStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *ID  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FlagAll bool `protobuf:"varint,2,opt,name=FlagAll,proto3" json:"FlagAll,omitempty"`
}

func (x *PluginStartRequest) Reset() {
	*x = PluginStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStartRequest) ProtoMessage() {}

func (x *PluginStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStartRequest.ProtoReflect.Descriptor instead.
func (*PluginStartRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PluginStartRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PluginStartRequest) GetFlagAll() bool {
	if x != nil {
		return x.FlagAll
	}
	return false
}

type PluginStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *ID  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FlagAll bool `protobuf:"varint,2,opt,name=FlagAll,proto3" json:"FlagAll,omitempty"`
}

func (x *PluginStopRequest) Reset() {
	*x = PluginStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStopRequest) ProtoMessage() {}

func (x *PluginStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStopRequest.ProtoReflect.Descriptor instead.
func (*PluginStopRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PluginStopRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PluginStopRequest) GetFlagAll() bool {
	if x != nil {
		return x.FlagAll
	}
	return false
}

// cmd: plugin uninstall
type PluginUninstallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *ID  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FlagAll       bool `protobuf:"varint,2,opt,name=FlagAll,proto3" json:"FlagAll,omitempty"`
	FlagDependent bool `protobuf:"varint,3,opt,name=FlagDependent,proto3" json:"FlagDependent,omitempty"`
}

func (x *PluginUninstallRequest) Reset() {
	*x = PluginUninstallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginUninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginUninstallRequest) ProtoMessage() {}

func (x *PluginUninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginUninstallRequest.ProtoReflect.Descriptor instead.
func (*PluginUninstallRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PluginUninstallRequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PluginUninstallRequest) GetFlagAll() bool {
	if x != nil {
		return x.FlagAll
	}
	return false
}

func (x *PluginUninstallRequest) GetFlagDependent() bool {
	if x != nil {
		return x.FlagDependent
	}
	return false
}

// cmd: plugin upload
type PluginUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filepath string `protobuf:"bytes,1,opt,name=Filepath,proto3" json:"Filepath,omitempty"`
}

func (x *PluginUploadRequest) Reset() {
	*x = PluginUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginUploadRequest) ProtoMessage() {}

func (x *PluginUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginUploadRequest.ProtoReflect.Descriptor instead.
func (*PluginUploadRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *PluginUploadRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

// cmd: plugin meta
type PluginMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                  *PluginID `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FlagDeps            bool      `protobuf:"varint,2,opt,name=FlagDeps,proto3" json:"FlagDeps,omitempty"`
	FlagDepsStatus      bool      `protobuf:"varint,3,opt,name=FlagDepsStatus,proto3" json:"FlagDepsStatus,omitempty"`
	FlagDependent       bool      `protobuf:"varint,4,opt,name=FlagDependent,proto3" json:"FlagDependent,omitempty"`
	FlagDependentStatus bool      `protobuf:"varint,5,opt,name=FlagDependentStatus,proto3" json:"FlagDependentStatus,omitempty"`
}

func (x *PluginMetaRequest) Reset() {
	*x = PluginMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetaRequest) ProtoMessage() {}

func (x *PluginMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetaRequest.ProtoReflect.Descriptor instead.
func (*PluginMetaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *PluginMetaRequest) GetID() *PluginID {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *PluginMetaRequest) GetFlagDeps() bool {
	if x != nil {
		return x.FlagDeps
	}
	return false
}

func (x *PluginMetaRequest) GetFlagDepsStatus() bool {
	if x != nil {
		return x.FlagDepsStatus
	}
	return false
}

func (x *PluginMetaRequest) GetFlagDependent() bool {
	if x != nil {
		return x.FlagDependent
	}
	return false
}

func (x *PluginMetaRequest) GetFlagDependentStatus() bool {
	if x != nil {
		return x.FlagDependentStatus
	}
	return false
}

type PluginMetaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArrayPluginListWithoutStatus []*PluginListWithoutStatus `protobuf:"bytes,1,rep,name=arrayPluginListWithoutStatus,proto3" json:"arrayPluginListWithoutStatus,omitempty"`
}

func (x *PluginMetaReply) Reset() {
	*x = PluginMetaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginMetaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetaReply) ProtoMessage() {}

func (x *PluginMetaReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetaReply.ProtoReflect.Descriptor instead.
func (*PluginMetaReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *PluginMetaReply) GetArrayPluginListWithoutStatus() []*PluginListWithoutStatus {
	if x != nil {
		return x.ArrayPluginListWithoutStatus
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

var file_plugin_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x10, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x44, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x56, 0x65, 0x72, 0x62, 0x6f,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x56, 0x65,
	0x72, 0x62, 0x6f, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50,
	0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x49, 0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65,
	0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65,
	0x70, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x14, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x49, 0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x56,
	0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x46, 0x6c,
	0x61, 0x67, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x6c, 0x61,
	0x67, 0x44, 0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x46, 0x6c, 0x61,
	0x67, 0x44, 0x65, 0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c, 0x22,
	0x3e, 0x0a, 0x16, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0xe1, 0x01, 0x0a, 0x11, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c, 0x12,
	0x1c, 0x0a, 0x09, 0x46, 0x6c, 0x61, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x46, 0x6c, 0x61, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x24, 0x0a,
	0x0d, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x0f, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f,
	0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x22, 0x96, 0x05, 0x0a, 0x14, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x06,
	0x6d, 0x65, 0x74, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x44, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x61, 0x49, 0x44,
	0x12, 0x26, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x42, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x11, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x35, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x43, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0x52,
	0x04, 0x43, 0x6f, 0x72, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x09, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52,
	0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0a,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61,
	0x67, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x6c, 0x61, 0x67,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x46, 0x6c, 0x61,
	0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x46,
	0x6c, 0x61, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x46, 0x6c, 0x61, 0x67, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x28,
	0x0a, 0x0f, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x67,
	0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x46, 0x6c, 0x61, 0x67, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0xcb, 0x03, 0x0a,
	0x17, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x6f,
	0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x61,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x49, 0x44, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x61, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x06,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x42, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x69, 0x65, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x11, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x20, 0x0a, 0x04, 0x43, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x72,
	0x65, 0x12, 0x2f, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x05, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0a, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x22, 0x79, 0x0a, 0x0f, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x69, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x34, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0x31, 0x0a, 0x13, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x49, 0x44, 0x52, 0x02, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x12, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x6c,
	0x61, 0x67, 0x41, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x46, 0x6c, 0x61,
	0x67, 0x41, 0x6c, 0x6c, 0x22, 0x49, 0x0a, 0x11, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74,
	0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49,
	0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c, 0x22,
	0x74, 0x0a, 0x16, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49,
	0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x6c, 0x6c, 0x12,
	0x24, 0x0a, 0x0d, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x74, 0x22, 0x31, 0x0a, 0x13, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x22, 0xd1, 0x01, 0x0a, 0x11, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70, 0x73, 0x12, 0x26, 0x0a, 0x0e,
	0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x46, 0x6c, 0x61,
	0x67, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x46, 0x6c,
	0x61, 0x67, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x46, 0x6c, 0x61, 0x67, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x76, 0x0a, 0x0f,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x63, 0x0a, 0x1c, 0x61, 0x72, 0x72, 0x61, 0x79, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x1c, 0x61, 0x72, 0x72, 0x61, 0x79, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData = file_plugin_proto_rawDesc
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_proto_rawDescData)
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_plugin_proto_goTypes = []interface{}{
	(*PluginGetRequest)(nil),        // 0: plugin.PluginGetRequest
	(*PluginPullRequest)(nil),       // 1: plugin.PluginPullRequest
	(*PluginInstallRequest)(nil),    // 2: plugin.PluginInstallRequest
	(*PluginInterfaceRequest)(nil),  // 3: plugin.PluginInterfaceRequest
	(*PluginListRequest)(nil),       // 4: plugin.PluginListRequest
	(*PluginListWithStatus)(nil),    // 5: plugin.PluginListWithStatus
	(*PluginListWithoutStatus)(nil), // 6: plugin.PluginListWithoutStatus
	(*PluginListReply)(nil),         // 7: plugin.PluginListReply
	(*PluginRemoveRequest)(nil),     // 8: plugin.PluginRemoveRequest
	(*PluginStartRequest)(nil),      // 9: plugin.PluginStartRequest
	(*PluginStopRequest)(nil),       // 10: plugin.PluginStopRequest
	(*PluginUninstallRequest)(nil),  // 11: plugin.PluginUninstallRequest
	(*PluginUploadRequest)(nil),     // 12: plugin.PluginUploadRequest
	(*PluginMetaRequest)(nil),       // 13: plugin.PluginMetaRequest
	(*PluginMetaReply)(nil),         // 14: plugin.PluginMetaReply
	(*ID)(nil),                      // 15: common.ID
	(*Author)(nil),                  // 16: plugin.Author
	(*Dependencies)(nil),            // 17: plugin.Dependencies
	(*Description)(nil),             // 18: plugin.Description
	(*Core)(nil),                    // 19: plugin.Core
	(*Interface)(nil),               // 20: plugin.Interface
	(*License)(nil),                 // 21: plugin.License
	(*Links)(nil),                   // 22: plugin.Links
	(*Repository)(nil),              // 23: plugin.Repository
	(*ErrorReply)(nil),              // 24: common.ErrorReply
	(*PluginID)(nil),                // 25: plugin.PluginID
}
var file_plugin_proto_depIdxs = []int32{
	15, // 0: plugin.PluginGetRequest.Id:type_name -> common.ID
	15, // 1: plugin.PluginPullRequest.Id:type_name -> common.ID
	15, // 2: plugin.PluginInstallRequest.Id:type_name -> common.ID
	15, // 3: plugin.PluginListWithStatus.metaID:type_name -> common.ID
	16, // 4: plugin.PluginListWithStatus.Author:type_name -> plugin.Author
	17, // 5: plugin.PluginListWithStatus.DependenciesArray:type_name -> plugin.Dependencies
	18, // 6: plugin.PluginListWithStatus.Description:type_name -> plugin.Description
	19, // 7: plugin.PluginListWithStatus.Core:type_name -> plugin.Core
	20, // 8: plugin.PluginListWithStatus.Interface:type_name -> plugin.Interface
	21, // 9: plugin.PluginListWithStatus.License:type_name -> plugin.License
	22, // 10: plugin.PluginListWithStatus.Links:type_name -> plugin.Links
	23, // 11: plugin.PluginListWithStatus.Repository:type_name -> plugin.Repository
	15, // 12: plugin.PluginListWithoutStatus.metaID:type_name -> common.ID
	16, // 13: plugin.PluginListWithoutStatus.Author:type_name -> plugin.Author
	17, // 14: plugin.PluginListWithoutStatus.DependenciesArray:type_name -> plugin.Dependencies
	18, // 15: plugin.PluginListWithoutStatus.Description:type_name -> plugin.Description
	19, // 16: plugin.PluginListWithoutStatus.Core:type_name -> plugin.Core
	20, // 17: plugin.PluginListWithoutStatus.Interface:type_name -> plugin.Interface
	21, // 18: plugin.PluginListWithoutStatus.License:type_name -> plugin.License
	22, // 19: plugin.PluginListWithoutStatus.Links:type_name -> plugin.Links
	23, // 20: plugin.PluginListWithoutStatus.Repository:type_name -> plugin.Repository
	5,  // 21: plugin.PluginListReply.Data:type_name -> plugin.PluginListWithStatus
	24, // 22: plugin.PluginListReply.ErrorPlugin:type_name -> common.ErrorReply
	15, // 23: plugin.PluginRemoveRequest.Id:type_name -> common.ID
	15, // 24: plugin.PluginStartRequest.Id:type_name -> common.ID
	15, // 25: plugin.PluginStopRequest.Id:type_name -> common.ID
	15, // 26: plugin.PluginUninstallRequest.Id:type_name -> common.ID
	25, // 27: plugin.PluginMetaRequest.ID:type_name -> plugin.PluginID
	6,  // 28: plugin.PluginMetaReply.arrayPluginListWithoutStatus:type_name -> plugin.PluginListWithoutStatus
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_common_proto_init()
	file_plugin_meta_information_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginPullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginInstallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginInterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginListWithStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginListWithoutStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginUninstallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginMetaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_rawDesc = nil
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
